import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Roboto, Inter } from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import Coin98AdapterProvider from "@/providers/Coin98WalletProvider";
import Coin98AdapterModal from "@/providers/Coin98AdapterModal";
import AppProvider from "@/providers/AppProvider";
import { Toaster } from "@/components/ui/toaster"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  // variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  // variable: "--font-geist-mono",
});

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} antialiased`}
      >
        <Coin98AdapterProvider>
          <AppProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              {/* <Layout>{children}</Layout> */}
              {children}
            </ThemeProvider>
          </AppProvider>
          <Coin98AdapterModal />
        </Coin98AdapterProvider>
        <Toaster />
      </body>
    </html>
  );
}
