import { CHAIN_TYPE } from "./chainIds";
import { COIN_IMAGE } from "./chainUtils";

export const LIST_CHAINS_SUPPORT = [
  CHAIN_TYPE.binanceSmart,
  CHAIN_TYPE.matic,
  CHAIN_TYPE.ether,
  CHAIN_TYPE.tomo,
  CHAIN_TYPE.solana,
  CHAIN_TYPE.optimism,
  CHAIN_TYPE.arbitrum,
];

export const DAPP_FILTER_KEY = "dapp_filter";

export const LIST_WALLET_SUPPORT = [
  {
    name: "coin98",
    title: "Coin98 Wallet",
    description: "Multichain",
    logo: "/images/logos/coin98.svg",
    link: "https://chrome.google.com/webstore/detail/coin98-wallet/aeachknmefphepccionboohckonoeemg",
    chainSupport: LIST_CHAINS_SUPPORT,
    isSupportMobile: true,
  },
];

export const QUERY_KEYS = {
  coinData: "coinData",
  dappV2: "dappV2",
  genre: "genre",
  gates: "gates",
  userSummary: "userSummary",
  addressSummary: "addressSummary",
  addressActiveSummary: "addressActiveSummary",
  totalAddressSummary: "totalAddressSummary",
  swapVolume: "swapVolume",
  swapVolumeSummary: "swapVolumeSummary",
  volume: "volume",
  volumeSummary: "volumeSummary",
  dashboard: "dashboard",
  funds: "funds",
  history: "history",
  amm: "amm",
  create_amm: "create_amm",
  fiat: "fiat",
  editFiat: "editFiat",
  multiSig: "multiSig",
  whatsNew: "whatsNew",
  events: "events",
  terms: "terms",
  policy: "policy",
  logs: "logs"
};

export const VALID_CHAIN = [
  CHAIN_TYPE.ether,
  CHAIN_TYPE.terra,
  CHAIN_TYPE.near,
  CHAIN_TYPE.kava,
  CHAIN_TYPE.tron,
  CHAIN_TYPE.elrond,
  CHAIN_TYPE.solana,
  CHAIN_TYPE.bitcoin,
  CHAIN_TYPE.cosmos,
  CHAIN_TYPE.sei,
  CHAIN_TYPE.sui,
  CHAIN_TYPE.seiMainnet,
  CHAIN_TYPE.aura,
  CHAIN_TYPE.ether,
  CHAIN_TYPE.chiliz,
  CHAIN_TYPE.injective,
  // CHAIN_TYPE["injective-888"],
  CHAIN_TYPE.celestia,
  CHAIN_TYPE.ton,
  CHAIN_TYPE.ancient8TestnetV2,
  CHAIN_TYPE.ancient8Mainnet,
];

export const CHAIN_DATA = {
  bitkub: {
    numChainId: 96,
    chainId: "0x60",
    // numLoad: 1,
    isBridge: false,
    isToken: true,
    isSupportedNFT: true,
    trcToken: "KAP-20",
    nftToken: "KAP721",
    isWeb3: true,
    isFee: true,
    image: "bitkub",
    balances: "0x4d461b38d1753386D4d6797F79441Ed0adC2f6F8",
    id: "bitkub-coin",
    name: "Bitkub Chain",
    shortName: "Bitkub",
    imageLink: COIN_IMAGE.KUB,
    symbol: "KUB",
    chain: "bitkub",
    // trcName: 'TOMO TRC21',
    rpcURL: "https://rpc.bitkubchain.io",
    scan: "https://www.bkcscan.com",
  },
  zeta: {
    id: "zetachain",
    numChainId: 7001,
    chainId: "0x1b59",
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    tokenStandard: "MRC20",
    nftStandard: "MRC721",
    name: "ZetaChain Testnet",
    shortName: "zeta",
    image: "zeta",
    imageLink: COIN_IMAGE.ZETA,
    symbol: "ZETA",
    chain: CHAIN_TYPE.zeta,
    environment: "testnet",

    standard: "MRC20 MRC721",
    rpcURL: "https://rpc.ankr.com/zetachain_evm_athens_testnet",
    scan: "https://explorer.zetachain.com/",
    scanTxPrefix: "evm/tx",
  },
  zetaMainnet: {
    id: "zetaMainnet",
    numChainId: 7000,
    chainId: "0x1b58",
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    tokenStandard: "MRC20",
    nftStandard: "MRC721",
    name: "ZetaChain Mainnet",
    shortName: "zeta",
    image: "zeta",
    imageLink: COIN_IMAGE.ZETA,
    symbol: "ZETA",
    chain: CHAIN_TYPE.zetaMainnet,
    environment: "mainnet",

    standard: "MRC20 MRC721",
    rpcURL: "https://zetachain-evm.blockpi.network/v1/rpc/public",
    scan: "https://explorer.mainnet.zetachain.com",
    scanTxPrefix: "evm/tx",
  },
  humanode: {
    id: "humanode",
    numChainId: 5234,
    chainId: "0x1472",
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    tokenStandard: "MRC20",
    nftStandard: "MRC721",
    name: "Humanode",
    shortName: "Humanode",
    image: "humanode",
    imageLink: COIN_IMAGE.HUMANODE,
    symbol: "eHMND",
    chain: CHAIN_TYPE.humanode,

    standard: "MRC20 MRC721",
    rpcURL: "https://explorer-rpc-http.mainnet.stages.humanode.io",
    scan: "https://humanode.subscan.io",
  },
  opBNB: {
    id: "binancecoin",
    numChainId: 204,
    chainId: "0xcc",
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    tokenStandard: "MRC20",
    nftStandard: "MRC721",
    name: "opBNB",
    shortName: "opBNB",
    image: "binance",
    imageLink: COIN_IMAGE.BNB,
    symbol: "BNB",
    chain: CHAIN_TYPE.opBNB,

    standard: "MRC20 MRC721",
    rpcURL: "https://opbnb-mainnet-rpc.bnbchain.org/",
    replacementSymbol: "opBNB",
    scan: "https://opbnbscan.com",
  },
  shardeum: {
    id: "shardeum",
    numChainId: 8081,
    chainId: "0x1f91",
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    tokenStandard: "MRC20",
    nftStandard: "MRC721",
    name: "Shardeum",
    shortName: "Shardeum",
    image: "shardeum",
    imageLink: COIN_IMAGE.SHARDEM,
    symbol: "SHM",
    chain: CHAIN_TYPE.shardeum,
    environment: "testnet",

    standard: "MRC20 MRC721",
    rpcURL: "https://dapps.shardeum.org/",
    scan: "https://explorer-dapps.shardeum.org/",
  },
  "97": {
    kind: "evm",
    key: "97",
    numChainId: 97,
    decimals: 18,
    chainId: "0x61",
    numLoad: 1,
    isBridge: true,
    isToken: true,
    isSupportedNFT: true,
    imageLink: COIN_IMAGE.BNB,
    nftToken: "BEP721",
    trcToken: "BEP20",
    symbolSpecial: "BSC",
    balances: "0xA6762c710852681c4593C10c4304C5211FB2122c",
    multisend: "0x2E1D30460265bFEBedacf5bb6f9A80F0E74B7498",
    nftMint: "0x2418400d29F8B774E49e93C5cb54460ae5Ecd788",
    stake: "0x08ac9c38ce078b9b81e5ab5bf8aafc3d2db94385",
    subName: "BSC",
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: "binance",
    id: "binancecoin",
    name: "BNB Smart Chain testnet",
    shortName: "BSC",
    symbol: "BNB",
    chain: "97",
    trcName: "BNB BEP20",
    rpcURL: "https://data-seed-prebsc-1-s1.binance.org:8545/",
    scan: "https://testnet.bscscan.com/",
    launchpadFactory: "0x8F94EAb4bF74CD9934B056031A97F502009eBfB8",
    launchpadMintableKey:
      "0x444f313053c893c305c4a5f333f3b033d548405c830016c4b623e787aa045145",
    launchpadTransferableKey:
      "0x1bc7992855b26a5ae511e9b448c90941ef8f1b835f4936d94c8cfd9202da9384",
  },
  multiChain: {
    isOther: true,
    isMnemonic: true,
    name: "Multi-Chain",
    image: "multi_chain",
    chain: CHAIN_TYPE.multiChain,
    trcName: "All Blockchains",
  },
  evm: {
    isOther: true,
    name: "EVM Wallet",
    image: "evm",
    chain: CHAIN_TYPE.evm,
    trcName: "EVM Wallet",
  },
  hardwareWallet: {
    isOther: true,
    isHardware: true,
    name: "Hardware Wallet",
    image: "ledger",
    chain: CHAIN_TYPE.hardwareWallet,
    trcName: "Import hardware wallet",
  },
  customCreate: {
    isOther: true,
    name: "Custom Network",
    image: "custom_network",
    chain: CHAIN_TYPE.customCreate,
    trcName: "Create Custom Network",
  },
  custom: {
    isOther: true,
    name: "Custom Network",
    image: "box",
    chain: CHAIN_TYPE.custom,
    trcName: "Custom Network",
  },
  binanceSmartTest: {
    isOther: true,
    numChainId: 97,
    chainId: "0x61",
    rpcURL: "https://data-seed-prebsc-1-s1.binance.org:8545",
  },
  bitcoin: {
    numLoad: 5,
    isFee: true,
    isMnemonic: true,
    image: "bitcoin",
    id: "bitcoin",
    name: "Bitcoin",
    shortName: "Bitcoin",
    imageLink: COIN_IMAGE.BTC,
    symbol: "BTC",
    chain: CHAIN_TYPE.bitcoin,
    trcName: "BTC",
    scan: "https://www.blockchain.com/btc",
  },
  ether: {
    kind: "evm",
    key: "ether",
    numChainId: 1,
    chainId: "0x1",
    numLoad: 0,
    isSupportedEIP1559: true,
    decimals: 18,
    isToken: true,
    isBridge: true,
    isSupportedNFT: true,
    trcToken: "ERC20",
    nftToken: "ERC721",
    balances: "0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6",
    multisend: "0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6",
    stake: "0x836bf46520C373Fdc4dc7E5A3bAe735d13bD44e3",
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: "ethereum",
    id: "ethereum",
    name: "Ethereum",
    shortName: "Ethereum",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.ether,
    trcName: "ETH ERC20 ERC721",
    rpcURL:
      "https://eth-mainnet.nodereal.io/v1/955ab7c09f78437981a573b43061fe10",
    scan: "https://etherscan.io",
  },
  etherPoW: {
    numChainId: 10001,
    chainId: "0x2711",
    numLoad: 0,
    isSupportedEIP1559: true,
    isToken: true,
    isBridge: true,
    isSupportedNFT: true,
    trcToken: "ERC20W",
    nftToken: "ERC721W",
    balances: "0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6",
    multisend: "0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6",
    stake: "0x836bf46520C373Fdc4dc7E5A3bAe735d13bD44e3",
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: "ethereum_pow",
    id: "ethereum-pow-iou",
    name: "Ethereum PoW",
    shortName: "ETHPoW",
    imageLink: COIN_IMAGE.ETHW,
    symbol: "ETHW",
    chain: CHAIN_TYPE.etherPoW,
    trcName: "ETHW ERC20W ERC721W",
    rpcURL: "https://mainnet.ethereumpow.org",
    scan: "https://www.oklink.com/en/ethw",
  },
  binanceSmart: {
    kind: "evm",
    key: "binanceSmart",
    decimals: 18,
    numChainId: 56,
    chainId: "0x38",
    numLoad: 1,
    isBridge: true,
    isToken: true,
    isSupportedNFT: true,
    nftToken: "BEP721",
    trcToken: "BEP20",
    symbolSpecial: "BSC",
    balances: "0xA6762c710852681c4593C10c4304C5211FB2122c",
    multisend: "0x2E1D30460265bFEBedacf5bb6f9A80F0E74B7498",
    nftMint: "0xc4cAd0938256ABA4417c565044Be2c2EB77096cb",
    stake: "0x08ac9c38ce078b9b81e5ab5bf8aafc3d2db94385",
    subName: "BSC",
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: "binance",
    id: "binancecoin",
    name: "BNB Smart Chain",
    shortName: "BSC",
    imageLink: COIN_IMAGE.BNB,
    symbol: "BNB",
    chain: CHAIN_TYPE.binanceSmart,
    trcName: "BNB BEP20",
    rpcURL: "https://binance.llamarpc.com",
    scan: "https://bscscan.com",
  },
  heco: {
    numChainId: 128,
    chainId: "0x80",
    numLoad: 1,
    isToken: true,
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    trcToken: "HRC20",
    nftToken: "HRC721",
    isWeb3: true,
    isFee: true,
    image: "heco",
    balances: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    nftMint: "0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF",
    id: "huobi-token",
    name: "HECO Chain",
    shortName: "Huobi",
    imageLink: COIN_IMAGE.HT,
    symbol: "HT",
    chain: CHAIN_TYPE.heco,
    trcName: "HT HRC20",
    rpcURL: "https://http-mainnet.hecochain.com",
    scan: "https://hecoinfo.com",
  },
  ancient8: {
    replacementSymbol: "ANCIENT8",
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    numChainId: 2863311531,
    chainId: "0xaaaaaaab",
    tokenStandard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "ancient8",
    environment: "testnet",
    isL2: true,
    name: "Ancient8 Testnet",
    shortName: "ETH",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.ancient8,
    standard: "ERC20 ERC721",
    rpcURL: "https://rpc-testnet.ancient8.gg",
    scan: "https://testnet.a8scan.io",
  },
  ancient8Mainnet: {
    balanceContract: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multiTransferContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    replacementSymbol: "ANCIENT8",
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    numChainId: 888888888,
    chainId: "0x34fb5e38",
    tokenStandard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "ancient8",
    isL2: true,
    name: "Ancient8",
    shortName: "ETH",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.ancient8Mainnet,
    standard: "ERC20 ERC721",
    rpcURL: "https://rpc.ancient8.gg",
    scan: "https://scan.ancient8.gg",
  },
  linea: {
    replacementSymbol: "LINEA",
    numChainId: 59144,
    chainId: "0xe708",
    tokenStandard: "LRC20",
    nftStandard: "LRC721",
    isWeb3: true,
    isFee: true,
    image: "linea",

    id: "ethereum",
    name: "Linea",
    shortName: "ETH",
    imageLink: COIN_IMAGE.ETH,
    isL2: true,
    symbol: "ETH",
    chain: CHAIN_TYPE.linea,
    standard: "LRC20 LRC721",
    rpcURL: "https://1rpc.io/linea",
    scan: "https://lineascan.build",
  },
  taiko: {
    replacementSymbol: "TAIKO",
    numChainId: 167007,
    chainId: "0x28c5f",
    tokenStandard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "taiko",
    name: "Taiko Jolnir Testnet",
    shortName: "ETH",
    isL2: true,
    environment: "devnet",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.taiko,
    standard: "ERC20 ERC721",
    rpcURL: "https://rpc.jolnir.taiko.xyz",
    scan: "https://explorer.jolnir.taiko.xyz",
  },
  kroma: {
    replacementSymbol: "KROMA",
    numChainId: 255,
    chainId: "0xff",
    tokenStandard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    isL2: true,
    image: "kroma",

    id: "ethereum",
    name: "Kroma",
    shortName: "ETH",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.kroma,
    standard: "ERC20 ERC721",
    rpcURL: "https://api.kroma.network",
    scan: "https://blockscout.kroma.network",
  },
  coreDao: {
    numChainId: 1116,
    chainId: "0x45c",
    tokenStandard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "coredao",

    id: "coredaoorg",
    name: "Core",
    shortName: "CORE",
    imageLink: COIN_IMAGE.CHZ,
    symbol: "CORE",
    chain: CHAIN_TYPE.coreDao,
    standard: "ERC20 ERC721",
    rpcURL: "https://rpc.coredao.org",
    scan: "https://scan.coredao.org",
  },
  okex: {
    numChainId: 66,
    chainId: "0x42",
    numLoad: 2,
    isSupportedNFT: true,
    balances: "0x5c93f4b35d3dd97ef481881aa33d00f76806fdad",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    nftMint: "0xAE12C5930881c53715B369ceC7606B70d8EB229f",
    isToken: true,
    id: "oec-token",
    name: "OKXChain",
    image: "okex",
    symbol: "OKT",
    chain: CHAIN_TYPE.okex,
    imageLink: COIN_IMAGE.OKT,
    icon: "okex",
    trcToken: "KIP20",
    nftToken: "NFT",
    trcName: "OKT KIP10 KIP20 NFT",
    isFee: true,
    isWeb3: true,
    rpcURL: "https://exchainrpc.okex.org",
    scan: "https://www.oklink.com/okexchain",
  },
  terra2: {
    prefix: "terra",
    numPath: 330,
    numLoad: 3,
    isToken: true,
    trcToken: "CW20",
    isCosmos: true,
    isMemo: true,
    id: "terra-luna-2",
    name: "Terra 2.0",
    image: "terra2",
    symbol: "LUNA",
    denom: "uluna",
    imageLink: COIN_IMAGE.LUNA2,
    chain: CHAIN_TYPE.terra2,
    trcName: "LUNA CW20",
    scan: "https://finder.terra.money/mainnet/",
    chainId: "phoenix-1",
  },
  gate: {
    numChainId: 86,
    chainId: "0x56",
    numLoad: 2,
    balances: "0x5c93f4b35d3dd97ef481881aa33d00f76806fdad",
    multisend: "0x963e1bcd1f82724bd8fa16a3b6962d100fb287fc",
    nftMint: "0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF",
    isSupportedNFT: true,
    isToken: true,
    id: "gatechain-token",
    name: "GateChain",
    image: "gate",
    symbol: "GT",
    chain: CHAIN_TYPE.gate,
    imageLink: COIN_IMAGE.GT,
    icon: "gate",
    trcToken: "GRC20",
    nftToken: "GRC721",
    trcName: "GT GRC20 GRC721",
    isFee: true,
    isWeb3: true,
    rpcURL: "https://evm.gatenode.cc",
    scan: "https://gatescan.org",
  },
  kucoin: {
    numChainId: 321,
    chainId: "0x141",
    numLoad: 2,
    isToken: true,
    subName: "KCS",
    trcToken: "KRC20",
    nftToken: "KRC721",
    balances: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    nftMint: "0xAE12C5930881c53715B369ceC7606B70d8EB229f",
    isWeb3: true,
    isSupportedNFT: true,
    isFee: true,
    image: "kucoin",
    id: "kucoin-shares",
    name: "KuCoin Community Chain",
    shortName: "Kucoin",
    imageLink: COIN_IMAGE.KCS,
    symbol: "KCS",
    chain: CHAIN_TYPE.kucoin,
    trcName: "KCS KRC20 KRC721",
    rpcURL: "https://rpc-mainnet.kcc.network",
    scan: "https://explorer.kcc.io/en",
  },
  solana: {
    numLoad: 1,
    isToken: true,
    trcToken: "SPL",
    nftToken: "SPL NFT",
    multisend: true,
    isBridge: true,
    isSupportedNFT: true,
    image: "solana",
    id: "solana",
    name: "Solana",
    shortName: "Solana",
    imageLink: COIN_IMAGE.SOL,
    symbol: "SOL",
    chain: CHAIN_TYPE.solana,
    trcName: "SOL SPL",
    rpcURL: "https://information.coin98.com/solanaV4",
    scan: "https://solscan.io",
    chainId: "solana"
  },
  near: {
    numLoad: 2,
    isToken: true,
    trcToken: "NEP141",
    image: "near",
    id: "near",
    name: "Near",
    imageLink: COIN_IMAGE.NEAR,
    symbol: "NEAR",
    trcName: "NEAR NEP141",
    chain: CHAIN_TYPE.near,
    scan: "https://explorer.near.org",
    rpcURL: "https://public-rpc.blockpi.io/http/near",
    // rpcURL: 'https://rpc.mainnet.near.org',
    scanTxs: "transactions",
    scanAddr: "accounts",
  },
  avax: {
    isSupportedEIP1559: true,
    numPath: 9000,
    isBridge: true,
    numChainId: 43114,
    chainId: "0xa86a",
    numLoad: 1,
    isSupportedNFT: true,
    isToken: true,
    trcToken: "ARC20",
    nftToken: "ARC721",
    symbolSpecial: "CCHAIN",
    balances: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
    multisend: "0xAE12C5930881c53715B369ceC7606B70d8EB229f",
    nftMint: "0x0eCE57A677D5e72D1ad45774239e23463CF1d743",
    subName: "C",
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: "avalancher",
    id: "avalanche-2",
    name: "Avalanche C-Chain",
    shortName: "Avalanche",
    imageLink: COIN_IMAGE.AVAX,
    symbol: "AVAX",
    chain: CHAIN_TYPE.avax,
    trcName: "AVAX-C ARC20",
    rpcURL: "https://api.avax.network/ext/bc/C/rpc",
    scan: "https://snowtrace.io",
  },
  avaxX: {
    numLoad: 5,
    isBridge: true,
    symbolSpecial: "XCHAIN",
    subName: "X",
    image: "avalancher",
    id: "avalanche-2",
    name: "Avalanche X-Chain",
    shortName: "Avalanche",
    imageLink: COIN_IMAGE.AVAX,
    symbol: "AVAX",
    chain: CHAIN_TYPE.avaxX,
    trcName: "AVAX-X",
    scan: "https://avascan.info/blockchain/x",
  },
  tron: {
    numLoad: 1,
    isToken: true,
    isBridge: true,
    trcToken: "TRC20",
    trcSubName: "TRC10",
    image: "tron",
    id: "tron",
    name: "Tron",
    shortName: "Tron",
    imageLink: COIN_IMAGE.TRX,
    symbol: "TRX",
    chain: CHAIN_TYPE.tron,
    trcName: "TRX TRC10 TRC20",
    scan: "https://tronscan.org/#",
    scanTxs: "transaction",
  },
  matic: {
    kind: "evm",
    key: "matic",
    // isSupportedEIP1559: true,
    numChainId: 137,
    chainId: "0x89",
    numLoad: 2,
    decimals: 18,
    isToken: true,
    trcToken: "PRC20",
    nftToken: "PRC721",
    isSupportedV2: true,
    isSupportedNFT: true,
    isFee: true,
    isWeb3: true,
    balances: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
    multisend: "0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF",
    nftMint: "0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E",
    id: "matic-network",
    name: "Polygon",
    image: "polygon",
    imageLink: COIN_IMAGE.MATIC,
    symbol: "MATIC",
    chain: CHAIN_TYPE.matic,
    trcName: "MATIC PRC20",
    rpcURL: "https://rpc-mainnet.maticvigil.com",
    scan: "https://polygonscan.com",
  },
  fantom: {
    numChainId: 250,
    chainId: "0xFA",
    numLoad: 2,
    isSupportedV2: true,
    isToken: true,
    isSupportedNFT: true,
    trcToken: "FRC20",
    nftToken: "FRC721",
    balances: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
    multisend: "0x5c93f4b35d3dd97ef481881aa33d00f76806fdad",
    nftMint: "0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF",
    isFee: true,
    isWeb3: true,
    id: "fantom",
    name: "Fantom",
    image: "fantom",
    imageLink: COIN_IMAGE.FTM,
    symbol: "FTM",
    chain: CHAIN_TYPE.fantom,
    trcName: "FANTOM FRC20",
    rpcURL: "https://rpcapi.fantom.network",
    scan: "https://ftmscan.com",
  },
  xDai: {
    isSupportedEIP1559: true,
    numChainId: 100,
    chainId: "0x64",
    numLoad: 2,
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    nftMint: "0xAE12C5930881c53715B369ceC7606B70d8EB229f",
    isSupportedNFT: true,
    isToken: true,
    id: "xdai",
    name: "Gnosis Chain",
    image: "xDai",
    symbol: "XDAI",
    chain: CHAIN_TYPE.xDai,
    imageLink: COIN_IMAGE.XDAI,
    icon: "xDai",
    trcToken: "XRC20",
    nftToken: "XRC721",
    trcName: "XDAI XRC20",
    isFee: true,
    isWeb3: true,
    rpcURL: "https://rpc.xdaichain.com",
    scan: "https://blockscout.com/xdai/mainnet",
  },
  polkadot: {
    isPolkadot: true,
    numLoad: 3,
    image: "polkadot",
    isMnemonic: true,
    id: "polkadot",
    name: "Polkadot",
    shortName: "Polkadot",
    imageLink: COIN_IMAGE.DOT,
    symbol: "DOT",
    chain: CHAIN_TYPE.polkadot,
    trcName: "DOT",
    rpcURL: "rpc.polkadot.io",
    scan: "https://polkadot.subscan.io",
    scanTxs: "extrinsic",
    scanAddr: "account",
  },
  kusama: {
    isPolkadot: true,
    numLoad: 3,
    image: "kusama",
    isMnemonic: true,
    id: "kusama",
    name: "Kusama",
    shortName: "Kusama",
    imageLink: COIN_IMAGE.KSM,
    symbol: "KSM",
    chain: CHAIN_TYPE.kusama,
    trcName: "KSM",
    rpcURL: "kusama-rpc.polkadot.io",
    scan: "https://kusama.subscan.io",
  },
  cosmos: {
    prefix: "cosmos",
    numPath: 118,
    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,
    chainId: "cosmoshub-4",
    id: "cosmos",
    name: "Cosmos",
    image: "cosmos",
    symbol: "ATOM",
    imageLink: COIN_IMAGE.ATOM,
    chain: CHAIN_TYPE.cosmos,
    trcName: "ATOM",
    scan: "https://www.mintscan.io/cosmos",
    scanTxs: "txs",
    scanAddr: "account",
    scanBlocks: "blocks/id",
  },
  thor: {
    prefix: "thor",
    numPath: 931,
    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: "thorchain",
    name: "THORChain",
    image: "thorchain",
    imageLink: COIN_IMAGE.RUNE,
    symbol: "RUNE",
    chain: CHAIN_TYPE.thor,
    trcName: "RUNE",
    scan: "https://viewblock.io/thorchain",
  },

  // Dynamic chain config only
  aura: {
    prefix: "aura",
    numPath: 118,
    nftToken: "CW721",
    numLoad: 1,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: true,
    isSupportedNFT: true,
    isDynamic: true,
    chainId: "aura",
    id: "aura-network",
    name: "Aura Xstaxy Mainnet",
    image: "aura_network",
    symbol: "AURA",
    imageLink: COIN_IMAGE.AURA,
    chain: CHAIN_TYPE.aura,
    trcName: "AURA CW-20 CW-721",
    scan: "https://aurascan.io",
    rpcURL: "https://rpc.aura.network",
    restURL: "https://lcd.aura.network",
    scanTxs: "transaction",
    scanAddr: "account",
  },
  terra: {
    prefix: "terra",
    numPath: 330,
    numLoad: 3,
    isToken: true,
    trcToken: "CW20",
    isCosmos: true,
    isMemo: true,
    id: "terra-luna",
    name: "Old Terra",
    image: "terra",
    symbol: "LUNC",
    denom: "uluna",
    imageLink: COIN_IMAGE.LUNA,
    chain: CHAIN_TYPE.terra,
    trcName: "LUNC CW20",
    scan: "https://finder.terra.money/columbus-5",
    chainId: "columbus-5",
  },
  band: {
    prefix: "band",
    numPath: 494,
    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: "band-protocol",
    name: "BandChain",
    image: "band",
    imageLink: COIN_IMAGE.BAND,
    symbol: "BAND",
    trcName: "BAND",
    chain: CHAIN_TYPE.band,
    scan: "https://cosmoscan.io",
    scanAddr: "account",
  },
  kava: {
    prefix: "kava",
    numPath: 459,
    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,
    id: "kava",
    name: "Kava",
    image: "kava",
    imageLink: COIN_IMAGE.KAVA,
    symbol: "KAVA",
    chain: CHAIN_TYPE.kava,
    trcName: "KAVA",
    scan: "https://www.mintscan.io/kava",
    scanTxs: "txs",
    scanAddr: "account",
    scanBlocks: "blocks/id",
  },
  secretNetwork: {
    prefix: "secret",
    numPath: 529,
    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,
    chainId: "secret-4",
    id: "secret",
    name: "Secret Network",
    image: "secret_network",
    imageLink: COIN_IMAGE.SCRT,
    symbol: "SCRT",
    chain: CHAIN_TYPE.secretNetwork,
    trcName: "SCRT",
    scan: "https://secretnodes.com/secret/chains/secret-4",
    scanTxs: "transactions",
    scanAddr: "account",
    scanBlocks: "blocks/id",
  },
  persistence: {
    prefix: "persistence",
    numPath: 750,
    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,
    chainId: "core-1",
    id: "persistence",
    name: "Persistence",
    image: "-persistence",
    imageLink: COIN_IMAGE.XPRT,
    symbol: "XPRT",
    chain: CHAIN_TYPE.persistence,
    trcName: "XPRT",
    scan: "https://explorer.persistence.one",
    scanBlocks: "blocks",
    scanTxs: "transactions",
    scanAddr: "wallet",
  },

  binance: {
    prefix: "bnb",
    numPath: 714,
    decimals: 18,
    numLoad: 2,
    isToken: true,
    trcToken: "BEP2",
    symbolSpecial: "BC",
    isCosmos: true,
    isMemo: true,
    subName: "BC",
    image: "binance",
    id: "binancecoin",
    name: "BNB Beacon Chain",
    shortName: "Binance",
    imageLink: COIN_IMAGE.BNB,
    symbol: "BNB",
    chain: CHAIN_TYPE.binance,
    trcName: "BNB BEP2 BEP8",
    scan: "https://explorer.binance.org",
  },
  functionX: {
    prefix: "fx",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,

    chainId: "fxcore",
    id: "fx-coin",
    name: "Function X",
    image: "functionX",
    symbol: "FX",
    imageLink: COIN_IMAGE.FX,
    chain: CHAIN_TYPE.functionX,
    trcName: "FX FXRC20",
    scan: "https://explorer.functionx.io/fxcore",
    rpcURL: "https://fx-json.functionx.io:26657",
    scanTxs: "tx",
    scanAddr: "address",
  },
  elrond: {
    isLibrary: true,

    prefix: "erd",
    numPath: 508,
    nftToken: "SFT",
    numLoad: 3,
    feeDefault: 0.00005,
    isToken: true,
    trcToken: "ESDT",

    id: "elrond-erd-2",
    name: "Elrond",
    image: "elrond",
    imageLink: COIN_IMAGE.EGLD,
    symbol: "EGLD",
    chain: CHAIN_TYPE.elrond,
    trcName: "EGLD ESDT SFT",
    scan: "https://explorer.elrond.com",
    scanTxs: "transactions",
    scanAddr: "accounts",
    scanBlocks: "blocks",
  },
  tezos: {
    isLibrary: true,
    feeDefault: 0.0015,

    prefix: "tz1",
    numPath: 1729,
    nftToken: "FA2",
    isToken: true,
    trcToken: "FA1.2",
    numLoad: 2,

    id: "tezos",
    name: "Tezos",
    image: "tezos",
    imageLink: COIN_IMAGE.XTZ,
    symbol: "XTZ",
    rpcURL:
      "https://nd-980-936-622.p2pify.com/e6ea03e1d3a5bcc4297e43c13622a905",
    chain: CHAIN_TYPE.tezos,
    trcName: "XTZ FA1.2 FA2",
    scan: "https://tezblock.io",
    scanTxs: "transaction",
    scanAddr: "account",
    scanBlocks: "block",
  },
  celo: {
    // mainAddress: '0x471ece3750da237f93b8e339c536989b8978a438',
    numPath: 52752,

    numChainId: 42220,
    chainId: "0xA4EC",

    numLoad: 1,
    isSupportedNFT: true,
    isFee: true,
    isToken: true,
    balances: "0x5c93f4b35d3dd97ef481881aa33d00f76806fdad",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    nftMint: "0xAE12C5930881c53715B369ceC7606B70d8EB229f",
    isWeb3: true,
    nftToken: "CELO721",
    image: "celo",
    id: "celo",
    name: "Celo",
    shortName: "Celo",
    imageLink: COIN_IMAGE.CELO,
    symbol: "CELO",
    chain: CHAIN_TYPE.celo,
    trcName: "CELO CUSD",
    rpcURL: "https://forno.celo.org",
    scan: "https://explorer.celo.org",
  },
  tomo: {
    kind: "evm",
    key: "tomo",
    numPath: 889,
    numChainId: 88,
    decimals: 18,
    chainId: "0x58",
    numLoad: 2,
    isBridge: true,
    isToken: true,
    isSupportedNFT: true,
    trcToken: "VRC25",
    nftToken: "TRC725",
    isWeb3: true,
    isFee: true,
    image: "vic",
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    // multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: "0xAE12C5930881c53715B369ceC7606B70d8EB229f",

    id: "tomochain",
    name: "Viction",
    shortName: "Viction",
    imageLink: COIN_IMAGE.TOMO,
    symbol: "VIC",
    chain: CHAIN_TYPE.tomo,
    trcName: "VRC25",
    rpcURL: "https://rpc.tomochain.com",
    scan: "https://vicscan.xyz",
  },
  algorand: {
    // feeDefault: ALGORAND_MIN_TX_FEE,

    trcToken: "ALGO",
    nftToken: "ALGO721",
    isToken: true,
    id: "algorand",
    name: "Algorand",
    image: "algorand",
    imageLink: COIN_IMAGE.ALGO,
    symbol: "ALGO",
    chain: CHAIN_TYPE.algorand,
    trcName: "ALGO ALGO721",
    scan: "https://algoexplorer.io",
  },
  casper: {
    trcToken: "CSPR",
    nftToken: "CSPR-NFT",
    id: "casper-network",
    name: "Casper",
    image: "casper",
    isMemo: true,
    imageLink: COIN_IMAGE.CSPR,
    symbol: "CSPR",
    chain: CHAIN_TYPE.casper,
    trcName: "CSPR",
    scanTxs: "deploy",
    scanAddr: "account",
    scan: "https://cspr.live",
  },
  kardia: {
    numChainId: 24,
    chainId: "0x18",

    numLoad: 2,
    isToken: true,
    id: "kardiachain",
    name: "KardiaChain",
    image: "kardia",
    symbol: "KAI",
    chain: CHAIN_TYPE.kardia,
    imageLink: COIN_IMAGE.KAI,
    icon: "kardia",
    subName: "KAI",
    trcToken: "KRC20",
    nftToken: "KRC721",
    trcName: "KAI KRC20 KRC721",
    balances: "0x8ef3C4Bf105Ec17cbeD7615C5711d2F4D44a4194",
    multisend: "0xf21201135568A81c9046d60a003eC2B883173F2f",
    nftMint: "0x8347CD0aaF874259e9d577BeE08231F648C3fc29",

    isFee: true,
    isWeb3: true,
    rpcURL: "https://rpc.kardiachain.io",
    scan: "https://explorer.kardiachain.io",
  },
  ronin: {
    prefix: "ronin:",
    numChainId: 2020,
    chainId: "0x7e4",

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    id: "ronin",
    name: "Ronin",
    image: "ronin",
    nftToken: "RRC721",
    symbol: "RON",
    chain: CHAIN_TYPE.ronin,
    imageLink: COIN_IMAGE.RON,
    icon: "ronin",
    trcToken: "RRC20",
    trcName: "RON RRC20 RRC721",
    isFee: true,
    isWeb3: true,
    rpcURL: "https://api.roninchain.com/rpc",
    scan: "https://explorer.roninchain.com",
  },

  klaytn: {
    numChainId: 8217,
    chainId: "0x2019",

    numLoad: 2,
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5c93f4b35d3dd97ef481881aa33d00f76806fdad",

    isSupportedNFT: true,
    isToken: true,
    id: "klay-token",
    name: "Klaytn",
    image: "klaytn",
    symbol: "KLAY",
    trcToken: "KIP7",
    nftToken: "KIP37",

    chain: CHAIN_TYPE.klaytn,
    imageLink: COIN_IMAGE.KLAY,
    icon: "klaytn",
    trcName: "KLAY KIP7 KIP37",
    isFee: true,
    isWeb3: true,
    scan: "https://scope.klaytn.com",
    rpcURL: "https://kaikas.cypress.klaytn.net:8651",
    scanAddr: "account",
  },
  harmony: {
    prefix: "one",
    numChainId: 1666600000,
    chainId: "0x63564C40",
    numLoad: 1,
    isToken: true,
    isSupportedNFT: true,
    nftToken: "HRC721",
    trcToken: "HRC20",
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E",
    nftMint: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",

    isWeb3: true,
    isFee: true,
    image: "harmony",

    id: "harmony",
    name: "Harmony",
    imageLink: COIN_IMAGE.ONE,
    symbol: "ONE",
    chain: CHAIN_TYPE.harmony,
    trcName: "ONE HRC20 HRC721",
    rpcURL: "https://api.harmony.one",
    scan: "https://explorer.harmony.one",
  },
  conflux: {
    isLibrary: true,
    feeDefault: 0.00005,

    prefix: "cfx",
    trcToken: "CRC20",
    nftToken: "CRC721",
    isToken: true,
    numLoad: 2,

    id: "conflux-token",
    name: "Conflux",
    image: "conflux",
    imageLink: COIN_IMAGE.CFX,
    symbol: "CFX",
    chain: CHAIN_TYPE.conflux,
    trcName: "CFX CRC20 CRC721",
    scan: "https://www.confluxscan.io",
    scanTxs: "transaction",
    scanAddr: "address",
    scanBlocks: "block",
  },
  mantle: {
    id: "mantle",
    numChainId: 5000,
    chainId: "0x1388",
    isL2: true,
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: "MRC20",
    nftStandard: "MRC721",
    name: "Mantle",
    shortName: "Mantle",
    icon: "app_mantle",
    imageLink: COIN_IMAGE.MNT,
    symbol: "MNT",
    chain: CHAIN_TYPE.mantle,
    image: "mantle",
    multiTransferContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",

    tokenStandard: "MRC20 MRC721",
    rpcURL: "http://rpc.mantle.xyz/",
    scan: "https://explorer.mantle.xyz/",
  },
  manta: {
    key: "manta",
    id: "manta",
    numChainId: 169,
    chainId: "0xa9",
    isL2: true,
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: "MRC20",
    nftStandard: "MRC721",
    name: "Manta Pacific",
    shortName: "Manta Pacific",
    icon: "manta",
    imageLink: COIN_IMAGE.MNT,
    symbol: "ETH",
    chain: CHAIN_TYPE.manta,
    image: "manta",
    tokenStandard: "MRC20 MRC721",
    rpcURL: "https://pacific-rpc.manta.network/http",
    scan: "https://explorer.mantle.xyz/",
  },
  scroll: {
    id: "ethereum",
    numChainId: 534352,
    chainId: "0x82750",
    isL2: true,
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    tokenStandard: "MRC20",
    nftStandard: "MRC721",
    name: "Scroll",
    shortName: "Scroll",
    image: "scroll",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.scroll,
    replacementSymbol: "SCROLL",

    standard: "MRC20 MRC721",
    rpcURL: "https://rpc.scroll.io/",
    scan: "https://scrollscan.com/",
  },
  scrollTestnet: {
    id: "ethereum",
    numChainId: 534353,
    chainId: "0x82751",
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: "SRC20",
    nftStandard: "SRC721",
    environment: "testnet",
    name: "Scroll Alpha Testnet",
    shortName: "Scroll",
    image: "scroll",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    replacementSymbol: "SCROLL",
    // symbolSpecial: 'SCROLL',
    chain: CHAIN_TYPE.scrollTestnet,
    rapidNetwork: true,

    tokenStandard: "SRC20 SRC721",
    rpcURL: "https://scroll-testnet.blockpi.network/v1/rpc/public",
    scan: "https://blockscout.scroll.io/",
  },
  nautilus: {
    id: "zebec-protocol",
    numChainId: 22222,
    chainId: "0x56ce",
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: "NRC20",
    nftStandard: "NRC721",
    name: "Nautilus mainnet",
    shortName: "ZBC",
    image: "nautilus",
    imageLink: COIN_IMAGE.ZBC,
    symbol: "ZBC",
    chain: CHAIN_TYPE.nautilus,
    tokenStandard: "NRC20 NRC721",
    rpcURL: "https://api.nautilus.nautchain.xyz",
    scan: "https://nautscan.com/",
  },
  optimism: {
    // defaultGas: 882000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    isBridge: true,
    numChainId: 10,
    chainId: "0xA",
    // numChainId: 69,
    // chainId: '0x45',

    numLoad: 2,
    isToken: true,
    trcToken: "ERC20 OPT",
    nftToken: "ERC721 OPT",
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: "optimism",
    id: "ethereum",
    name: "Optimism",
    shortName: "Optimism",
    imageLink: COIN_IMAGE.OP,
    symbol: "ETH",
    symbolSpecial: "OP",
    chain: CHAIN_TYPE.optimism,
    trcName: "ETH ERC20 ERC721",
    rpcURL: "https://mainnet.optimism.io",
    // rpcURL: 'https://kovan.optimism.io',
    scan: "https://optimistic.etherscan.io",
  },
  boba: {
    // defaultGas: 80000000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    isBridge: true,
    numChainId: 288,
    chainId: "0x120",
    // numChainId: 28,
    // chainId: '0x1C',

    numLoad: 2,
    isToken: true,
    trcToken: "ERC20 BOBA",
    nftToken: "ERC721 BOBA",
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: "boba",
    id: "ethereum",
    name: "Boba Network",
    shortName: "Boba Network",
    imageLink: COIN_IMAGE.BOBA,
    symbol: "ETH",
    symbolSpecial: "BOBA",
    chain: CHAIN_TYPE.boba,
    trcName: "ETH ERC20 ERC721",
    rpcURL: "https://mainnet.boba.network",
    scan: "https://blockexplorer.boba.network",
  },
  zkSyncPolygon: {
    numChainId: 1101,
    chainId: "0x44D",
    numLoad: 0,
    isToken: true,
    isSupportedNFT: true,

    trcToken: "ERC20",
    nftToken: "ERC721",
    balances: "0x8bfcbf5cbb6729c11ccb2949C149D8928b6C932C",
    multisend: "0xafb9013228D365AcEE408543B284240F7965EDDD",
    nftMint: "0x8437BF9557eE3a32e964a8Ff300DF69379d747a4",
    isWeb3: true,
    isFee: true,
    image: "zkSyncPolygon",
    id: "ethereum",
    name: "Polygon zkEVM",
    shortName: "Polygon zkEVM",
    symbolSpecial: "zkPolygon",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.zkSyncPolygon,
    trcName: "ETH ERC20 ERC721",
    rpcURL: "https://zkevm-rpc.com",
    scan: "https://zkevm.polygonscan.com",
  },
  zkSyncEra: {
    symbolSpecial: "zkEra",
    numChainId: 324,
    chainId: "0x144",
    numLoad: 0,
    isToken: true,
    isSupportedNFT: true,
    trcToken: "ERC20",
    nftToken: "ERC721",
    balances: "0xeAe3Fc95365C0F3258506c867E172f72450D69d7",
    multisend: "0xf518a374433Ea889d25f942A799F717D10Fd4A44",
    nftMint: "0x244f7dF740Cd37c5DBa635D52BF01146ACb56c28",
    isWeb3: true,
    isFee: true,
    image: "zkSyncEra",
    id: "ethereum",
    name: "zkSync Era",
    shortName: "zkSync Era",
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.zkSyncEra,
    trcName: "ETH ERC20 ERC721",
    rpcURL: "https://mainnet.era.zksync.io",
    scan: "https://explorer.zksync.io",
  },
  arbitrum: {
    // defaultGas: 7000000,
    isL2: true,
    isBridge: true,
    numChainId: 42161,
    chainId: "0xA4B1",
    // numChainId: 421611,
    // chainId: '0x66EEB',
    isSupportedNFT: true,
    numLoad: 2,
    isToken: true,
    trcToken: "ERC20 ARB",
    nftToken: "ERC721 ARB",
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    isWeb3: true,
    isFee: true,
    image: "arbitrum",
    id: "ethereum",
    name: "Arbitrum",
    shortName: "Arbitrum",
    imageLink: COIN_IMAGE.ETHARB,
    symbol: "ETH",
    symbolSpecial: "ARB",
    chain: CHAIN_TYPE.arbitrum,
    trcName: "ETH ERC20 ERC721",
    rpcURL: "https://arb1.arbitrum.io/rpc",
    // rpcURL: 'https://rinkeby.arbitrum.io/rpc',
    scan: "https://arbiscan.io",
  },
  arbitrumXdai: {
    isL2: true,
    numChainId: 200,
    chainId: "0xC8",

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    trcToken: "ERC20 AOX",
    nftToken: "ERC721 AOX",
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    nftMint: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",

    isWeb3: true,
    isFee: true,
    image: "arbitrum_xdai",
    id: "xdai",
    name: "Arbitrum on xDai",
    shortName: "Arbitrum on xDai",
    imageLink: COIN_IMAGE.ETHA0X,
    symbol: "XDAI",
    symbolSpecial: "AOX",
    chain: CHAIN_TYPE.arbitrumXdai,
    trcName: "XDAI XRC20 XRC721",
    rpcURL: "https://arbitrum.xdaichain.com",
    scan: "https://blockscout.com/xdai/aox",
  },
  aurora: {
    isL2: true,
    feeDefault: 0,

    numChainId: 1313161554,
    chainId: "0x4e454152",
    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    nftToken: "AURORA721",
    trcToken: "AURORA20",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    isWeb3: true,
    image: "aurora",

    id: "aurora-near",
    name: "Aurora",
    shortName: "Aurora",
    imageLink: COIN_IMAGE.AURORA,
    symbol: "AURORA ETH",
    chain: CHAIN_TYPE.aurora,
    trcName: "AURORA AURORA20 AURORA721",
    rpcURL:
      "https://aurora-mainnet.core.chainstack.com/863f618d49f8d2dfecfed48c8d74a374",
    scan: "https://explorer.mainnet.aurora.dev",
  },
  ton: {
    id: "the-open-network",
    name: "The Open Network",
    shortName: "TON",
    imageLink: COIN_IMAGE.TON,
    isToken: false,
    isMemo: true,
    symbol: "TON",
    chain: CHAIN_TYPE.ton,
    trcName: "TON TON721",
    rpcURL: "https://toncenter.com/api/v2/jsonRPC",
    scan: "https://tonscan.org",
    image: "ton",
    icon: "ton",
  },
  cronos: {
    id: "crypto-com-chain",
    chain: CHAIN_TYPE.cronos,
    name: "Cronos",
    shortName: "CRO",
    isToken: true,
    trcToken: "CRO",
    numChainId: 25,
    chainId: "0x19",
    symbol: "CRO",
    image: "cronos",
    trcName: "CRC20 CRC721",
    rpcURL: "https://evm-cronos.crypto.org",
    scan: "https://cronoscan.com",
    imageLink: COIN_IMAGE.CRO,
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    nftMint: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    multisend: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
  },
  bittorrent: {
    numChainId: 199,
    chainId: "0xc7",
    isToken: true,
    trcToken: "BTT",
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: "bittorrent",
    name: "BitTorrent Chain",
    shortName: "BTT",
    image: "bitorrent",
    imageLink: COIN_IMAGE.BTT,
    symbol: "BTT",
    chain: CHAIN_TYPE.bittorrent,
    trcName: "BTT BRC20 BRC721",
    balances: "0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019",
    nftMint: "0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    rpcURL: "https://rpc.bt.io",
    scan: "https://scan.bt.io/#",
    scanTxs: "transaction",
    scanAddr: "address",
  },
  theta: {
    trcToken: "THETA",
    id: "theta-token",
    name: "Theta Network",
    shortName: "THETA",
    image: "thetanetwork",
    imageLink: COIN_IMAGE.THETA,
    symbol: "THETA",
    chain: CHAIN_TYPE.theta,
    trcName: "TNT20 TNT721",
    rpcURL: "https://theta-bridge-rpc.thetatoken.org/rpc",
    scan: "https://explorer.thetatoken.org",
    scanTxs: "txs",
    scanAddr: "account",
    // isFee: true
  },
  thetaFuel: {
    numChainId: 361,
    chainId: "0x169",
    isToken: true,
    trcToken: "TFUEL",
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: "theta-fuel",
    name: "Theta Network EVM",
    shortName: "THETA",
    image: "thetanetwork",
    imageLink: COIN_IMAGE.TFUEL,
    symbol: "TFUEL",
    chain: CHAIN_TYPE.thetaFuel,
    trcName: "TNT20 TNT721",
    rpcURL: "https://eth-rpc-api.thetatoken.org/rpc",
    scan: "https://explorer.thetatoken.org",
    scanTxs: "txs",
    scanAddr: "account",
    balances: "0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019",
    nftMint: "0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9",
    multisend: "0xf7eee3a8363731c611a24cddfcbcade9c153cfe8",
  },
  platon: {
    numChainId: 210425,
    chainId: "0x335F9",
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    trcToken: "LAT",
    id: "platon-network",
    name: "PlatON Network",
    shortName: "LAT",
    image: "platon",
    imageLink: COIN_IMAGE.LAT,
    symbol: "LAT",
    chain: CHAIN_TYPE.platon,

    trcName: "PRC20 PRC721",
    rpcURL: "https://openapi2.platon.network/rpc",
    scan: "https://scan.platon.network",
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    nftMint: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    multisend: "0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC",
  },
  moonbeam: {
    numChainId: 1284,
    chainId: "0x504",
    isToken: true,
    trcToken: "GLMR",
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: "moonbeam",
    name: "Moonbeam",
    shortName: "GLMR",
    image: "moonbeam",
    imageLink: COIN_IMAGE.GLMR,
    symbol: "GLMR",
    chain: CHAIN_TYPE.moonbeam,
    trcName: "MERC20 MERC721",
    rpcURL: "https://rpc.api.moonbeam.network",
    scan: "https://moonscan.io",
    balances: "0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019",
    nftMint: "0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
  },
  aptosLabs: {
    chainId: "aptoslabs",
    // isToken: true,
    trcToken: "APT",
    id: "aptos",
    name: "Aptos",
    shortName: "APT",
    image: "aptos",
    imageLink: COIN_IMAGE.APT,
    symbol: "APT",
    chain: CHAIN_TYPE.aptosLabs,
    trcName: "APTOS AIT-3",
    rpcURL: "https://fullnode.mainnet.aptoslabs.com",
    scan: "https://tracemove.io",
    scanTxs: "transaction",
    scanAddr: "account",
  },
  injective: {
    kind: "cosmwasm",
    key: "injective",
    prefix: "inj",

    decimals: 18,
    numPath: 118,
    id: "injective-1",
    numChainId: "injective-1",
    chainId: "injective-1",
    name: "Injective",
    chain: "injective",
    denom: "inj",
    minimalDenom: "inj",
    nativeToken: "inj",
    symbol: "INJ",
    nftToken: "CW721",
    image: "injective",
    scan: "https://explorer.injective.network",
    rpcURL: "https://tm.injective.network",
    scanTxs: "transaction",
    scanAddr: "account",
    scanBlocks: "block",
  },

  "injective-888": {
    kind: "cosmwasm",
    key: "injective-888",
    prefix: "inj",

    decimals: 18,
    numPath: 118,
    id: "injective-888",
    numChainId: "injective-888",
    chainId: "injective-888",
    name: "Injective Testnet",
    chain: "injective-888",
    denom: "inj",
    minimalDenom: "inj",
    nativeToken: "inj",

    symbol: "INJ",
    nftToken: "CW721",
    image: "injective",
    scan: "https://testnet.explorer.injective.network",
    rpcURL: "https://testnet.sentry.tm.injective.network:443",
    scanTxs: "transaction",
    scanAddr: "contract",
    scanBlocks: "block",
  },
  osmosis: {
    prefix: "osmo",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "osmosis-1",
    id: "osmosis",
    name: "Osmosis",
    image: "omosis",
    symbol: "OSMO",
    imageLink: COIN_IMAGE.OSMO,
    chain: CHAIN_TYPE.osmosis,
    trcName: "OSMO",
    scan: "https://www.mintscan.io/osmosis",
    rpcURL: "https://rpc-osmosis.keplr.app",
    scanTxs: "txs",
    scanAddr: "account",
  },
  evmos: {
    prefix: "evmos",
    numPath: 60,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "evmos_9001-2",
    id: "evmos",
    name: "Evmos",
    image: "evmos",
    symbol: "EVMOS",
    imageLink: COIN_IMAGE.EVMOS,
    chain: CHAIN_TYPE.evmos,
    trcName: "EVMOS",
    scan: "https://www.mintscan.io/evmos",
    rpcURL: "https://tendermint.bd.evmos.org:26657",
    scanTxs: "txs",
    scanAddr: "account",
    isEthermint: true,
  },
  juno: {
    prefix: "juno",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "juno-1",
    id: "juno-network",
    name: "Juno Network",
    image: "juno",
    symbol: "JUNO",
    imageLink: COIN_IMAGE.JUNO,
    chain: CHAIN_TYPE.juno,
    trcName: "JUNO",
    scan: "https://www.mintscan.io/juno",
    rpcURL: "https://rpc-osmosis.keplr.app",
    scanTxs: "txs",
    scanAddr: "account",
  },
  agoric: {
    prefix: "agoric",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "agoric-3",
    id: "agoric",
    name: "Agoric",
    image: "agoric",
    symbol: "BLD",
    imageLink: COIN_IMAGE.BLD,
    chain: CHAIN_TYPE.agoric,
    trcName: "BLD",
    scan: "https://bigdipper.live/agoric",
    rpcURL: "https://rpc-agoric.keplr.app",
    scanTxs: "transactions",
    scanAddr: "accounts",
  },
  oasis: {
    numChainId: 42262,
    chainId: "0xa516",
    numLoad: 0,
    isToken: true,

    trcToken: "ORC20",
    nftToken: "ORC721",
    balances: "0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6",
    multisend: "0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6",

    isWeb3: true,
    isFee: true,
    image: "oasis",
    id: "oasis-network",
    name: "Oasis Network",
    shortName: "ROSE",
    imageLink: COIN_IMAGE.ROSE,
    symbol: "ROSE",
    chain: CHAIN_TYPE.oasis,
    trcName: "ROSE ORC20 ORC721",
    rpcURL: "https://emerald.oasis.dev",
    scan: "https://explorer.emerald.oasis.dev/",
    scanTxs: "tx",
    scanAddr: "address",
  },
  kujira: {
    prefix: "kujira",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "kaiyo-1",
    id: "kujira",
    name: "Kujira",
    image: "kujira",
    symbol: "KUJI",
    imageLink: COIN_IMAGE.KUJI,
    chain: CHAIN_TYPE.kujira,
    trcName: "KUJI",
    scan: "https://www.mintscan.io/kujira",
    rpcURL: "https://rpc.kaiyo.kujira.setten.io",
    scanTxs: "txs",
    scanAddr: "account",
  },
  stargaze: {
    prefix: "stars",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "stargaze-1",
    id: "stargaze",
    name: "Stargaze",
    image: "stagraze",
    symbol: "STARS",
    imageLink: COIN_IMAGE.STARS,
    chain: CHAIN_TYPE.stargaze,
    trcName: "STARS",
    scan: "https://www.mintscan.io/stargaze",
    rpcURL: "https://rpc-stargaze.keplr.app",
    scanTxs: "txs",
    scanAddr: "account",
  },
  umee: {
    prefix: "umee",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "umee-1",
    id: "umee",
    name: "Umee",
    image: "umee",
    symbol: "UMEE",
    imageLink: COIN_IMAGE.UMEE,
    chain: CHAIN_TYPE.umee,
    trcName: "UMEE",
    scan: "https://www.mintscan.io/umee",
    rpcURL: "https://rpc-umee.keplr.app",
    scanTxs: "txs",
    scanAddr: "account",
  },
  stride: {
    prefix: "stride",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: "stride-1",
    id: "stride",
    name: "Stride",
    image: "stride",
    symbol: "STRD",
    imageLink: COIN_IMAGE.STRD,
    chain: CHAIN_TYPE.stride,
    trcName: "STRD",
    scan: "https://www.mintscan.io/stride",
    rpcURL: "https://rpc-stride.keplr.app",
    scanTxs: "txs",
    scanAddr: "account",
  },
  baseTest: {
    isToken: true,
    isSupportedNFT: true,

    trcToken: "ERC20",
    nftToken: "ERC721",
    trcName: "ETH ERC20 ERC721",
    environment: "devnet",
    isDevnet: true,
    numChainId: 84531,
    chainId: "0x14A33",
    numLoad: 2,
    isFee: true,
    isWeb3: true,
    balances: "0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9",
    nftMint: "0xB3E382CA0562C4440f346768b9b20bA813d21FDb",
    multisend: "0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019",
    name: "Base (Testnet)",
    image: "ic-base",
    imageLink: COIN_IMAGE.BASE,
    symbol: "ETH",
    chain: CHAIN_TYPE.baseTest,
    rpcURL: "https://goerli.base.org",
    scan: "https://goerli.basescan.org",
  },
  base: {
    id: "ethereum",
    isToken: true,
    isSupportedNFT: true,

    trcToken: "ERC20",
    nftToken: "ERC721",
    trcName: "ETH ERC20 ERC721",
    // environment: "devnet",
    // isDevnet: true,
    numChainId: 8453,
    chainId: "0x2105",
    numLoad: 1,
    isFee: true,
    isWeb3: true,
    // balances: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    // nftMint: '0xB3E382CA0562C4440f346768b9b20bA813d21FDb',
    // multisend: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    name: "Base",
    image: "ic-base",
    imageLink: COIN_IMAGE.BASE,
    symbol: "ETH",
    chain: CHAIN_TYPE.base,
    rpcURL: "https://mainnet.base.org",
    scan: "https://basescan.org",
  },
  aptos: {
    environment: "devnet",
    // isDevnet: true,
    chainId: "ait-3",
    // isToken: true,
    trcToken: "APT",
    id: "aptos-test",
    name: "Aptos Testnet",
    shortName: "APT",
    image: "aptos",
    imageLink: COIN_IMAGE.APT,
    symbol: "APT-TEST",
    chain: CHAIN_TYPE.aptos,
    trcName: "APTOS AIT-3",
    rpcURL: "https://fullnode.testnet.aptoslabs.com",
    scan: "https://testnet.tracemove.io",
    scanTxs: "transaction",
    scanAddr: "account",
  },
  aptosDev: {
    environment: "devnetFull",
    isDevnet: true,
    chainId: "ait-dev",
    // isToken: true,
    trcToken: "APT",
    id: "aptos-dev",
    name: "Aptos DevNet",
    shortName: "APT",
    image: "aptos",
    imageLink: COIN_IMAGE.APT,
    symbol: "APT-DEV",
    chain: CHAIN_TYPE.aptosDev,
    trcName: "APTOS AIT-3",
    rpcURL: "https://fullnode.devnet.aptoslabs.com",
    scan: "https://devnet.tracemove.io",
    scanTxs: "transaction",
    scanAddr: "account",
  },
  suiMainnet: {
    chainId: "sui",
    trcToken: "SUI",
    isWeb3: true,
    id: "sui",
    name: "Sui",
    shortName: "Sui",
    image: "sui",
    imageLink: COIN_IMAGE.SUI,
    symbol: "SUI",
    chain: CHAIN_TYPE.sui,
    trcName: "SUI",
    rpcURL: "https://wallet-rpc.mainnet.sui.io/",
    scan: "https://explorer.sui.io",
    scanTxs: "transactions",
    scanAddr: "addresses",
  },

  // Old DevNet standard - tempory remove for stable version
  // sui: {
  //   environment: 'devnet',
  //   isDevnet: true,
  //   chainId: 'sui',
  //   trcToken: 'SUI',
  //   id: 'sui',
  //   name: 'Sui',
  //   shortName: 'Sui',
  //   image: 'app_sui',
  //   imageLink: COIN_IMAGE.SUI,
  //   symbol: 'SUI',
  //   chain: CHAIN_TYPE.sui,
  //   trcName: 'SUI',
  //   rpcURL: 'https://gateway.devnet.sui.io:443',
  //   scan: 'https://explorer.devnet.sui.io',
  //   scanTxs: 'transactions',
  //   scanAddr: 'addresses'
  // },

  seiMainnet: {
    kind: "cosmwasm",
    key: "seiMainnet",

    prefix: "sei",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    // isToken: true,
    isSupportedNFT: true,

    decimals: 6,
    numChainId: "pacific-1",
    chainId: "pacific-1",
    id: "sei",
    name: "Sei Mainnet",
    image: "sei",
    symbol: "SEI",
    imageLink: COIN_IMAGE.SEI,
    chain: CHAIN_TYPE.seiMainnet,
    trcName: "Sei Chain",
    nativeToken: "usei",

    scan: "https://seiscan.app/mainet",
    rpcURL: "https://information.c98staging.dev/api/sei",
    scanTxs: "transaction",
    scanAddr: "account",
  },
  sei: {
    kind: "cosmwasm",
    key: "sei",

    prefix: "sei",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    // isToken: true,
    isSupportedNFT: true,

    decimals: 6,
    numChainId: "atlantic-2",
    chainId: "atlantic-2",
    id: "sei",
    name: "Sei Testnet",
    image: "sei",
    symbol: "SEI",
    imageLink: COIN_IMAGE.SEI,
    chain: CHAIN_TYPE.sei,
    trcName: "Sei Chain",
    nativeToken: "usei",
    scan: "https://sei.explorers.guru/",
    rpcURL: "https://sei-testnet-rpc.polkachu.com",
    scanTxs: "txs",
    scanAddr: "accounts",
  },
  archway: {
    prefix: "archway",
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,
    isDevnet: true,

    chainId: "constantine-1",
    id: "constantine-1",
    name: "Archway",
    image: "archway",
    symbol: "CONST",
    imageLink: COIN_IMAGE.CONST,
    chain: CHAIN_TYPE.archway,
    trcName: "Constantine Testnet",
    scan: "https://explorer.constantine-1.archway.tech",
    rpcURL: "https://rpc.constantine-1.archway.tech",
    scanTxs: "transactions",
    scanAddr: "account",
  },
  chiliz: {
    numChainId: 88888,
    chainId: "0x15B38",
    numLoad: 2,
    // isToken: true,
    // isSupportedNFT: true,
    trcToken: "CAP20",
    nftToken: "CAP721",
    isWeb3: true,
    isFee: true,
    image: "chiliz",

    id: "chiliz",
    name: "Chiliz",
    shortName: "CHZ",
    imageLink: COIN_IMAGE.CHZ,
    symbol: "CHZ",
    chain: CHAIN_TYPE.chiliz,
    trcName: "CAP20 CAP721",
    rpcURL: "https://rpc.chiliz.com/",
    scan: "https://scan.chiliz.com/",
  },
  "11155111": {
    kind: "evm",
    key: "11155111",

    isWeb3: true,
    numChainId: 11155111,
    decimals: 18,
    chainId: "0xaa36a7",
    numLoad: 0,
    isSupportedEIP1559: true,
    isToken: true,
    isBridge: true,
    isSupportedNFT: true,

    trcToken: "ERC20",
    nftToken: "ERC721",

    isSupportedV2: true,
    isFee: true,
    image: "ethereum",
    id: "ethereum",
    name: "Sepolia(ETH) Ethereum",
    shortName: "Ethereum",
    symbol: "ETH",
    chain: "11155111",
    trcName: "ETH ERC20 ERC721",
    imageLink: COIN_IMAGE.ETH,
    rpcURL: "https://rpc.sepolia.org",
    scan: "https://sepolia.etherscan.io/",
  },
  celestia: {
    prefix: "celestia",
    path: 118,
    isFactory: true,
    isCosmos: true,
    isMemo: true,
    id: "celestia",
    chainId: "celestia",
    name: "Celestia",
    icon: "celestia",
    symbol: "TIA",
    logo: COIN_IMAGE.LUNA2,
    chain: CHAIN_TYPE.celestia,
    scan: "https://www.mintscan.io/celestia",
    scanTxPrefix: "tx",
    scanAddressPrefix: "account",
    isSupportedNFT: false,
    image: "celestia",
  },
  ancient8TestnetV2: {
    isFee: true,
    environment: "testnet",
    isWeb3: true,
    tokenStandard: "ERC20",
    icon: "ancient8",
    shortName: "ETH",
    isL2: true,
    logo: COIN_IMAGE.ETH,
    numChainId: 28122024,
    chainId: "0x1ad1ba8",
    name: "Ancient8 Testnet - Celestia",
    chain: CHAIN_TYPE.ancient8TestnetV2,
    symbol: "ETH",
    rpcURL: "https://rpcv2-testnet.ancient8.gg",
    scan: "https://scanv2-testnet.ancient8.gg",
    image: "ancient8",
  },
  kavaEvm: {
    replacementSymbol: "EVM",
    standard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    shortName: "KAVA",
    numChainId: 2222,
    chainId: "0x8ae",
    id: "kava",
    name: "Kava EVM",
    icon: "kava",
    symbol: "KAVA",
    logo: COIN_IMAGE.KAVA,
    chain: CHAIN_TYPE.kavaEvm,
    tokenStandard: "ERC20 ERC721",
    scan: "https://kavascan.com",
    rpcURL: "https://evm.kava.io",
    scanTxPrefix: "tx",
    image: "kava",
    scanAddressPrefix: "address",
  },
  confluxEvm: {
    replacementSymbol: "EVM",
    standard: "ERC20",
    nftStandard: "ERC721",
    isWeb3: true,
    isFee: true,
    shortName: "CFX",
    numChainId: 1030,
    chainId: "0x406",
    id: "conflux-token",
    name: "Conflux eSpace",
    icon: "conflux",
    image: "conflux",
    symbol: "CFX",
    logo: COIN_IMAGE.CFX,
    chain: CHAIN_TYPE.confluxEvm,
    tokenStandard: "ERC20 ERC721",
    scan: "https://evm.confluxscan.io",
    rpcURL: "https://evm.confluxrpc.com",
    scanTxPrefix: "tx",
    scanAddressPrefix: "address",
  },
  starknet: {
    path: "m/44'/9004'/0'/0/0",
    isEstimateGas: true,
    gasDefault: 0.00009,
    isHd: true,
    numPath: 0,
    isFee: true,
    isL2: true,
    isWeb3: true,
    symbolSpecial: "STARKNET",
    image: "starknet",
    icon: "starknet",
    id: "starknet",
    name: "Starknet",
    shortName: "Starknet",
    symbol: "ETH",
    chain: CHAIN_TYPE.starknet,
    trcName: "ETH",
    scan: "https://starkscan.co",
    scanTxs: "tx",
    scanAddr: "contract",
    addressLength: 66,
  },
  metis: {
    multiTransferContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    balanceContract: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    id: "metis-token",
    isToken: true,
    numChainId: 1088,
    chainId: "0x440",
    standard: "MRC20",
    nftStandard: "MRC721",
    isWeb3: true,
    isFee: true,
    icon: "metis",
    image: "metis",
    name: "Metis ",
    shortName: "METIS",
    symbol: "METIS",
    chain: CHAIN_TYPE.metis,
    tokenStandard: "MRC20 MRC721",
    rpcURL: "https://andromeda.metis.io/?owner=1088",
    scan: "https://andromeda-explorer.metis.io",
  },
  blast: {
    multiTransferContract: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    balanceContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    id: "ethereum",
    replacementSymbol: "BLAST",
    isToken: true,
    isL2: true,
    numChainId: 81457,
    chainId: "0x13E31",
    standard: "BRC20",
    nftStandard: "BRC721",
    isWeb3: true,
    isFee: true,
    icon: "blast",
    image: "blast",
    name: "Blast",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.blast,
    tokenStandard: "BRC20 BRC721",
    rpcURL: "https://rpc.blast.io",
    scan: "https://blastscan.io",
  },
  mode: {
    multiTransferContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    balanceContract: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    id: "ethereum",
    replacementSymbol: "MODE",
    isToken: true,
    isL2: true,
    numChainId: 34443,
    chainId: "0x868b",
    standard: "MRC20",
    nftStandard: "MRC721",
    isWeb3: true,
    isFee: true,
    icon: "mode",
    image: "mode",
    name: "Mode",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.mode,
    tokenStandard: "MRC20 MRC721",
    rpcURL: "https://mainnet.mode.network",
    scan: "https://explorer.mode.network",
  },
  zora: {
    multiTransferContract: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    balanceContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    id: "ethereum",
    replacementSymbol: "ZORA",
    isToken: true,
    isL2: true,
    numChainId: 7777777,
    chainId: "0x76adf1",
    standard: "ZRC20",
    nftStandard: "ZRC721",
    isWeb3: true,
    isFee: true,
    icon: "zora",
    image: "zora",
    name: "Zora",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.zora,
    tokenStandard: "ZRC20 ZRC721",
    rpcURL: "https://rpc.zora.energy",
    scan: "https://explorer.zora.energy",
  },
  victionTestnet: {
    environment: "testnet",
    numChainId: 89,
    chainId: "0x59",
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: "VRC25",
    nftStandard: "VRC725",
    isWeb3: true,
    isFee: true,
    icon: "vic",
    image: "vic",
    balanceContract: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multiTransferContract: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    name: "Viction Testnet",
    shortName: "VIC",
    logo: COIN_IMAGE.TOMO,
    symbol: "VIC",
    chain: CHAIN_TYPE.victionTestnet,
    tokenStandard: "VIC VRC25",
    rpcURL: "https://rpc-testnet.viction.xyz",
    scan: "https://testnet.vicscan.xyz",
  },
  zkFair: {
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    id: "usd-coin",
    symbolSpecial: "ZKFAIR",
    isToken: true,
    numChainId: 42766,
    chainId: "0xa70e",
    trcToken: "ZRC20",
    nftToken: "ZRC721",
    isWeb3: true,
    isFee: true,
    icon: "zkFair",
    image: "zkFair",
    name: "ZKFair",
    shortName: "USDC",
    symbol: "USDC",
    chain: CHAIN_TYPE.zkFair,
    trcName: "ZRC20 ZRC721",
    rpcURL: "https://rpc.zkfair.io",
    scan: "https://scan.zkfair.io",
  },
  omni: {
    balances: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    isToken: true,
    numChainId: 165,
    chainId: "0xa5",
    trcToken: "ORC20",
    nftToken: "OC721",
    isWeb3: true,
    isFee: true,
    icon: "omni",
    image: "omni",
    name: "Omni Testnet",
    shortName: "OMNI",
    symbol: "OMNI",
    chain: CHAIN_TYPE.omni,
    trcName: "ORC20 ORC721",
    rpcURL: "https://testnet.omni.network",
    scan: "https://testnet.explorer.omni.network",
  },
  orderly: {
    balances: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    id: "ethereum",
    symbolSpecial: "ORDERLY",
    isToken: true,
    isL2: true,
    numChainId: 291,
    chainId: "0x123",
    trcToken: "ORC20",
    nftToken: "ORC721",
    isWeb3: true,
    isFee: true,
    icon: "orderly",
    image: "orderly",
    name: "Orderly Network",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.orderly,
    trcName: "ORC20 ORC721",
    rpcURL: "https://rpc.orderly.network",
    scan: "https://explorer.orderly.network:443",
  },
  skate: {
    balances: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    multisend: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    symbolSpecial: "SKATE",
    isToken: true,
    isL2: true,
    numChainId: 5051,
    chainId: "0x13bb",
    trcToken: "SRC20",
    nftToken: "SRC721",
    isWeb3: true,
    isFee: true,
    icon: "skate",
    image: "skate",
    name: "Skatechain Testnet",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.skate,
    trcName: "SRC20 SRC721",
    rpcURL: "https://nollie-rpc.skatechain.org",
    scan: "https://nolliescan.skatechain.org",
  },
  wanchain: {
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    id: "wanchain",
    isToken: true,
    numChainId: 888,
    chainId: "0x378",
    trcToken: "WRC20",
    nftToken: "WRC721",
    isWeb3: true,
    isFee: true,
    icon: "wanchain",
    image: "wanchain",
    name: "Wanchain",
    shortName: "WAN",
    symbol: "WAN",
    chain: CHAIN_TYPE.wanchain,
    trcName: "WRC20 WRC721",
    rpcURL: "https://gwan-ssl.wandevs.org:56891",
    scan: "https://www.wanscan.org",
  },
  mint: {
    symbolSpecial: "MINT",
    numChainId: 185,
    chainId: "0xb9",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "mint",
    icon: "mint",
    name: "Mint Mainnet",
    shortName: "ETH",
    isL2: true,
    symbol: "ETH",
    chain: CHAIN_TYPE.mint,
    trcName: "ERC20 ERC721",
    rpcURL: "https://rpc.mintchain.io",
    scan: "https://explorer.mintchain.io:443",
  },
  iotex: {
    numChainId: 4689,
    chainId: "0x1251",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "iotex",
    icon: "iotex",
    name: "IoTeX Network",
    shortName: "IOTX",
    imageLink: COIN_IMAGE.ETH,
    symbol: "IOTX",
    chain: CHAIN_TYPE.iotex,
    trcName: "ERC20 ERC721",
    rpcURL: "https://rpc.ankr.com/iotex",
    scan: "https://iotexscan.io/",
  },
  zkLink: {
    symbolSpecial: "ZKLINK",
    numChainId: 810180,
    chainId: "0xc5cc4",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "zkLink",
    icon: "zkLink",
    name: "zkLink Nova",
    shortName: "ETH",
    isL2: true,
    imageLink: COIN_IMAGE.ETH,
    symbol: "ETH",
    chain: CHAIN_TYPE.zkLink,
    trcName: "ERC20 ERC721",
    rpcURL: "https://rpc.zklink.io",
    scan: "https://explorer.zklink.io",
  },
  neon: {
    isToken: true,
    numChainId: 245022934,
    chainId: "0xe9ac0d6",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "neon",
    icon: "neon",
    name: "Neon EVM",
    shortName: "NEON",
    symbol: "NEON",
    chain: CHAIN_TYPE.neon,
    trcName: "ERC20 ERC721",
    rpcURL: "https://neon-proxy-mainnet.solana.p2p.org",
    scan: "https://neonscan.org",
  },
  xLayer: {
    numChainId: 196,
    chainId: "0xc4",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    isFee: true,
    image: "xLayer",
    icon: "xLayer",
    name: "X Layer",
    shortName: "X Layer",
    symbol: "OKB",
    chain: CHAIN_TYPE.xLayer,
    trcName: "ERC20 ERC721",
    rpcURL: "https://rpc.xlayer.tech",
    scan: "https://www.okx.com/web3/explorer/xlayer",
  },
  taikoMainnet: {
    gasName: " Wei ",
    isToken: true,
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    isCrawlServices: true,
    id: "ethereum",
    symbolSpecial: "TAIKO",
    numChainId: 167000,
    chainId: "0x28c58",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    isFee: true,
    isL2: true,
    image: "taiko",
    icon: "taiko",
    name: "Taiko",
    shortName: "Taiko",
    symbol: "ETH",
    chain: CHAIN_TYPE.taikoMainnet,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://rpc.taiko.xyz",
    scan: "https://taikoscan.io",
  },
  auraEvm: {
    isToken: true,
    gasName: " Wei ",
    balances: "0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8",
    multisend: "0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD",
    id: "aura-network",
    symbolSpecial: "AURA EVM",
    numChainId: 6322,
    chainId: "0x18b2",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "aura_network",
    icon: "aura_network",
    name: "Aura Mainnet",
    shortName: "AURA",
    symbol: "AURA",
    chain: CHAIN_TYPE.auraEvm,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://jsonrpc.aura.network",
    scan: "https://aurascan.io",
  },
  cyber: {
    isL2: true,
    isToken: true,
    balances: "0x7ff3be07ffa286b2806ac458ce9982a73611537e",
    multisend: "0x6c041cd1e064a7845f7734bef42456c7e6b6e617",
    id: "ethereum",
    symbolSpecial: "CYBER",
    numChainId: 7560,
    chainId: "0x1d88",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "cyber",
    icon: "cyber",
    name: "Cyber",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.cyber,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://cyber-mainnet-archive.alt.technology",
    scan: "https://cyberscan.co",
  },
  xterio: {
    isL2: true,
    isToken: true,
    balances: "0x40A2b4d38a55afc5a6731c69b616326177D294Ce",
    multisend: "0x6c041CD1e064a7845f7734BEf42456c7E6b6E617",
    id: "ethereum",
    symbolSpecial: "XTERIO",
    numChainId: 2702128,
    chainId: "0x293b30",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "xterio",
    icon: "xterio",
    name: "Xterio",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.xterio,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://xterio-eth.alt.technology",
    scan: "https://eth.xterscan.io",
  },
  astar: {
    isL2: true,
    isToken: true,
    balances: "0xD4825105467044301bc6B89EcEA42Bde24F152FD",
    multisend: "0x40A2b4d38a55afc5a6731c69b616326177D294Ce",
    id: "ethereum",
    symbolSpecial: "ASTAR",
    numChainId: 3776,
    chainId: "0xec0",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "astar",
    icon: "astar",
    name: "Astar zkEVM",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.astar,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://rpc.startale.com/astar-zkevm",
    scan: "https://astar-zkevm.explorer.startale.com",
  },
  fraxtal: {
    isToken: true,
    balances: "0x40A2b4d38a55afc5a6731c69b616326177D294Ce",
    multisend: "0x6c041CD1e064a7845f7734BEf42456c7E6b6E617",
    id: "frax-ether",
    numChainId: 252,
    chainId: "0xfc",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "fraxtal",
    icon: "fraxtal",
    name: "Fraxtal",
    shortName: "Frax Ether",
    symbol: "frxETH",
    chain: CHAIN_TYPE.fraxtal,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://rpc.mainnet.frax.com/",
    scan: "https://fraxscan.com",
  },
  lightLink: {
    isL2: true,
    isToken: true,
    balances: "0x40A2b4d38a55afc5a6731c69b616326177D294Ce",
    multisend: "0x6c041CD1e064a7845f7734BEf42456c7E6b6E617",
    id: "ethereum",
    symbolSpecial: "LIGHTLINK",
    numChainId: 1890,
    chainId: "0x762",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "lightLink",
    icon: "lightLink",
    name: "Lightlink Phoenix",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.lightLink,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://replicator-01.phoenix.lightlink.io/rpc/v1",
    scan: "https://phoenix.lightlink.io",
  },
  orange: {
    isL2: true,
    isToken: true,
    balances: "0x7FF3BE07Ffa286B2806ac458cE9982A73611537E",
    multisend: "0xD4825105467044301bc6B89EcEA42Bde24F152FD",
    id: "bitcoin",
    symbolSpecial: "ORANGE",
    numChainId: 61022,
    chainId: "0xee5e",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "orange",
    icon: "orange",
    name: "Orange",
    shortName: "BTC",
    symbol: "BTC",
    chain: CHAIN_TYPE.orange,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://hk-rpc.orangechain.xyz",
    scan: "https://scan.orangechain.xyz",
  },
  zircuit: {
    isL2: true,
    isToken: true,
    balances: "0x40A2b4d38a55afc5a6731c69b616326177D294Ce",
    multisend: "0x6c041CD1e064a7845f7734BEf42456c7E6b6E617",
    // id: 'ethereum',
    symbolSpecial: "ZIRCUIT",
    numChainId: 48900,
    chainId: "0xbf04",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "zircuit",
    icon: "zircuit",
    name: "Zircuit",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.zircuit,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://zircuit1-mainnet.p2pify.com/",
    scan: "https://explorer.zircuit.com",
  },
  abstract: {
    isL2: true,
    // isToken: true,

    // balances: '0x6509A9977569413CE8baCa7C50BeA0F2F983E53B',
    // multisend: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    // id: 'ethereum',
    isDevnet: true,
    symbolSpecial: "ABSTRACT",
    numChainId: 11124,
    chainId: "0x2b74",
    trcToken: "ERC20",
    nftToken: "ERC721",
    isWeb3: true,
    image: "abstract",
    icon: "abstract",
    name: "Abstract",
    shortName: "ETH",
    symbol: "ETH",
    chain: CHAIN_TYPE.abstract,
    tokenStandard: "ERC20 ERC721",
    rpcURL: "https://api.testnet.abs.xyz",
    scan: "https://explorer.testnet.abs.xyz",
  },
};
